### ISSUE TITLE
Implement unit testing with catch2

### ISSUE THREAD

**Issue by maxsu** [maxsu/balancers2#13]
[Catch2](https://github.com/catchorg/Catch2) is a simple C++ unit testing framework with powerful features.

This will replace our test runner script, and make it easier to write and run unit tests.

## Documentation:
- [Overview](https://medium.com/dsckiit/a-guide-to-using-catch2-for-unit-testing-in-c-f0f5450d05fb)
- [Tutorial](https://github.com/catchorg/Catch2/blob/devel/docs/tutorial.md#top)
- [Reference docs](https://github.com/catchorg/Catch2/tree/devel/docs)
- [Command line options](https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#top)
  - [Specifying which test to run](https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#specifying-which-tests-to-run
)
  - [Working with a debugger](https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#breaking-into-the-debugger)

## Example test file

```c++
#include "catch.hpp"
#include "narwhal.hpp"

TEST_CASE( "Narwals are cute and fuzzy" ) {

  # Summon lemmy the narwal
  Narwhal lemmy = summonNarwhal('lemmy');

  SECTION( "Narwals are cute" ) {
    REQUIRE( lemmy.is_cute == true );
  }

  SECTION( "Narwhals are fuzzy" ) {
    REQUIRE( lemmy.is_fuzzy == true );
  }
```

## Tasks
- [ ] Import Catch2 header into project
- [ ] Create a main Catch2 file: test.cpp
  - [ ] Add a  `#define CONFIG_CATCH_MAIN` line
  - [ ] Add a `#include "catch.hpp"` line
- [ ] Format existing tests as Catch2 test files:
  - [ ] Add a `#include "catch.hpp"` line to each test file
  - [ ] Use`TEST_CASE("test description"){ ..test contents... }` to organize test cases 
  - [ ] Use `SECTION("section description"){ ..section contents..} ` to organize subsections of a test case
  - [ ] Use `REQUIRE( <boolean expression> );` to write test assertions
- [ ] Write a script or makefile to build and run the tests
- [ ] Learn how to debug test cases

**Comment by maxsu** [comment]
Ps. this issue rage inducing  (ノಠ益ಠノ彡 ) because it means we may have to say goodbye to our trusty old `test.sh`
