### ISSUE TITLE
Implement Linting

### ISSUE THREAD

**Issue by maxsu** [maxsu/balancers2#25]
Linting is static analysis that catches potential bugs and code quality issues.

# Requirements:
Things we need:

1. linter configs  - Allows us to disable false positives
2. linter scripts - Lets us call our linters from CI
3. Linting scope
   - What filetypes do we lint?   
   - What do we lint for?
   - Which linters will we use?

# Scope: File types

Our project could benefit from 3 kinds linting:
1. c++
6. shell script (for CI & build scripts)
7. markdown (for docs) 

# Scope: Linting Targets
## C++
We can lint C++ for a few types of things:
1. Style and readability
2. Bugs/Correctness
3. Performance
4. Security

Proposal: We should lint first for Style, then gradually enable linting for Bugs and Performance. Linting for security might be helpful for learning.

## bash, Markdown
We can lint markdown for style, and we can lint bash for style and  correctness.

Proposal: Enable all linting rules from the start.

# Scope: Linter selection

I propose these linters:
1. C++: `clang-tidy`
6. bash: `shellcheck`
7. markdown: `markdownlint`

# Tasks:

## Planning

- [ ] Decide locations for:
  - [ ]  linter configs 
  - [ ] linter scripts

- [ ] Decide linter languages
- [ ] Decide linter target scope
- [ ] Decide linter selection

## Implementation

C++:
- [ ] add linter
- [ ] config linter

bash:
- [ ] add linter
- [ ] config linter

markdown:
- [ ] add linter
- [ ] config linter

## Post-Launch

Make plans to:
- [ ] fix C++ lint issues
- [ ] graduate C++ linting scope 
- [ ] Add linting to CI
