### ISSUE TITLE
Proposal: Use the Pitchfork Layout (PFL)

### ISSUE THREAD

**Issue by maxsu** [maxsu/balancers2#26]
The [PFL spec](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs) is a sensible C++ project layout first introduced in a Reddit post humorously titled [Prepare Thy Pitchforks](https://www.reddit.com/r/cpp/comments/996q8o/prepare_thy_pitchforks_a_de_facto_standard/).

It makes many useful suggestions, including:

- [ ] Put public headers in `/includes`
  - [ ] Unless the project chooses [merged header placement](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs#src.header-placement.merged) 
- [ ] Put .cpp files in `/src`
- [ ] Put docs in `/docs`
- [ ] Put scripts and dev tools in `/tools`, including:
  - [ ] lint scripts
  - [ ] test scripts
  - [ ] move `/.vscode` to `/tools/vscode`
- [x] Put tests in `/tests` 
- [ ] Limit files in the project root to:
  - [ ] `README.md`
  - [x] LICENSE
  - [x] `.gitignore`
  - [ ] Build system files
  - [ ] other tool support files (like `.clang-format`) *may* live in the project root

I would like to implement these changes, and use PFL as our project layout structure.
