### ISSUE TITLE
Use Classes for Wiring behaviors

### ISSUE THREAD

**Issue by maxsu** [maxsu/balancers2#30]
`existsBalancer` currently encapsulates a couple behaviors it uses to generate wirings when extending flows:
- Phase I: [Exhaustively generate wirings](https://github.com/maxsu/balancers2/blob/main/lib/exists_balancer.cpp#L52-L69)
- Phase II: Prune these wirings according to feasibility criteria (eg., [drop circular dependencies](https://github.com/maxsu/balancers2/blob/main/lib/exists_balancer.cpp#L73-L101))

It would be nice to encapsulate these behaviors into classes.

# Design Proposal

- A `WiringGenerator` base class has a method `generate`
- A `ExhaustiveWiringGenerator` encapsulates generates all possible (phase I of our scenario)
- A `PrunedWiringGenerator` calls Phase I, then gets rid of infeasible wirings (phase II)
- `existsBalancers` depends on `PrunedWiringGenerator`

UML diagram:
```mermaid
 classDiagram
      direction TD
      WiringGenerator <|-- ExhaustiveWiringGenerator : implements
      WiringGenerator <|-- PrunedWiringGenerator : implements
      ExhaustiveWiringGenerator <-- PrunedWiringGenerator : depends on
      ExistsBalancer --> PrunedWiringGenerator: depends on
      <<abstract>> WiringGenerator
      WiringGenerator: &Flow
      WiringGenerator: Configs generateWirings()
```

# Tasks
- [ ] Extract existing wiring generators to functions
  - [ ] Phase I
  - [ ] Phase II
- [ ] Unit test existing wiring generators
  - [ ] Phase I
  - [ ] Phase II
- [ ] Write a `WiringGenerator` base class with a method `generate`
- [ ] Write a `ExhaustiveWiringGenerator` class to encapsulate part of our existing scenario (generates all possible configs)
- [ ] Write a `PrunedWiringGenerator` to encapsulate pruning behaviors (gets rid of infeasible wirings)
- [ ] Translate unit tests to new classes
- [ ] Refactor `existsBalancer` to new classes
- [ ] Drop old wiring generators and tests
