### ISSUE TITLE
Created new issues labels and other organizational things - Did I do it right?

### ISSUE THREAD

**Issue by exfret** [maxsu/balancers2#9]
I created some labels and organized and renamed some things. I want to know if I did it in a standard way (not just a way we would understand, but a way that a newcomer could understand). I think having a session to look over other C++ projects or looping in a more experienced developer could be helpful.

- [x] Max looks over the labels with me and we make any necessary immediate modifications
- [x] (Optional) We schedule a time to possibly meet with a more experienced developer for guidance

**Comment by maxsu** [comment]
I like this!

I have overhauled the labels a bit:

- [x] Lowercased names; use dashes '-' instead of spaces
- [x] Shortned descriptions
- [x] Renamed some labels to be more like VScode'
- [x] Added effort labels (experimental)
- [x] Added other labels (experimental)

Link: [Current Labels](https://github.com/maxsu/balancers2/issues/labels)


### Renames:

Meta -> question: Devevlopment questions and discussions
interface -> ux: User experience issues
(forgot) -> debt: Code quality issues
(forgot) -> runtime-bug: Runtime behavior issues 
(forgot) -> algorithm-bug: Algorithm correctness issue

### New labels:

3-effort, 5-effort, 8-effort, 13-effort: Relative effort to complete an issue
priority-high: High priority items
test-plan: Strategies for specific tests
 ノಠ益ಠノ彡: Rage inducing issues
engineering: Build, issue tracking, and tooling issues

**Comment by exfret** [comment]
Some of the labels could use more explaining for me. Let's discuss this today.

- [ ] Discuss Max's new labels.

**Comment by maxsu** [comment]
I've added two new labels:

`current-sprint`: The issues we'd like to close in the next 1-2 weeks. 

I've borrowed the sprint concept from [scrum](https://en.wikipedia.org/wiki/Scrum_(software_development)#Sprint). A sprint is a time-boxed effort, typically 1 to 2 weeks, with limited and focused goals.

`maybe-later`: Issues we close until (potentially) some later date.

The Wordpress project uses this as one of its [issue resolution types](https://make.wordpress.org/core/handbook/contribute/trac/#ticket-properties). 

```diff
Pro:
+ Less strict than tags like `out-of-scope` or `off-topic`.
Cons:
- Indecisive; can pollute our closed issues with issues of dubious value.
```
See also: The VsCode project [issue triage guide](https://github.com/microsoft/vscode/wiki/Issues-Triaging#closing-issues).

**Comment by maxsu** [comment]
I vote to close this issue as resolved!

Let me know if there are more label issues to discuss, or do the honors :+1:

**Comment by maxsu** [comment]
Closing issue! Feel free to create a new dx issue to propose a new tag
